project:
  type: website
  output-dir: .

website:
  title: "Yu-You Liou 劉昱佑"
  site-url: https://yyliou.github.io
  favicon: icon.png
  open-graph: true
  twitter-card: true
  image: pic.png
  description: "Yu-You Liou (劉昱佑) — PhD Fellow at National Taiwan University and Lecturer at Shih Chien University. Research in agricultural, environmental, urban and transportation economics."
  navbar:
    title: "Liou"
    left:
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: teach.qmd
        text: Teaching
      - href: projects.qmd
        text: Projects
      - href: extension.qmd
        text: Extension

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: false
    include-in-header: _header.html
    include-after-body: _footer.html

lang: en

editor: source

# quarto render
