project:
  type: website
  output-dir: .

website:
  title: "Yu-You Liou 劉昱佑"
  site-url: https://yyliou.github.io
  favicon: icon.png
  open-graph: true
  twitter-card: true
  image: pic.png
  description: "Yu-You Liou (劉昱佑) — Ph.D. Student at National Taiwan University and Adjunct Lecturer at Shih Chien University. Research in agricultural economics, environmental and resource economics, transportation economics, regional studies, and real estate price analysis."
  navbar:
    title: "Liou"
    left:
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: teach.qmd
        text: Teaching
      - href: https://yyliou.github.io/yyliou/cv/cv_metrics.pdf
        text: CV
        target: _blank

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: false
    include-in-header: _header.html
    include-after-body: _footer.html

lang: en

editor: source

# quarto render
