project:
  type: website
  output-dir: .

website:
  title: "Yu-You Liou 劉昱佑"
  favicon: icon.png
  navbar:
    title: "Liou"
    left:
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: teach.qmd
        text: Teaching
      - href: projects.qmd
        text: Projects

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: false
    include-in-header: _header.html
    include-after-body: _footer.html

editor: source

# quarto render
