#!/usr/bin/env python3
"""
Rebuild the GenWanMin (源雲明體) web fonts and their @font-face rules.

Each weight ships in two layers:

  fonts/GenWanMin2TW-<w>-sub.woff2
      Every character the site's pages use. Normally the only font file a
      browser downloads.
  fonts/fallback/GenWanMin2TW-<w>-<start>.woff2
      All Big5 Traditional Chinese characters and the font's symbols, cut
      into code-point blocks. A browser fetches a block only when a page
      shows a character the main subset lacks, so text added since the last
      rebuild still appears in GenWanMin instead of a system font.

The script also rewrites the generated @font-face block in styles.css.
The main subset comes last there, with its exact unicode-range, so
browsers check it first and use a fallback block only for characters it
does not hold. Font URLs carry a content hash, so browsers refetch a
font only when it changes.

Rerun after adding text, especially new Chinese characters, so the main
subset covers every page again.

Requires: fonttools, brotli   ->   pip install fonttools brotli

Usage:  python3 subset_fonts.py              rebuild the main subsets and styles.css
        python3 subset_fonts.py --fallback   also rebuild the fallback blocks
        python3 subset_fonts.py --check      list page characters the main subsets lack
"""
import argparse
import hashlib
import html
import os
import pathlib
import re
import sys
import textwrap
from concurrent.futures import ProcessPoolExecutor

from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = pathlib.Path(__file__).resolve().parent
FONT_DIR = ROOT / "fonts"
FALLBACK_DIR = FONT_DIR / "fallback"
STYLESHEET = ROOT / "styles.css"

FAMILY = "MyFont"
FONT_NAME = "GenWanMin2TW"
WEIGHTS = {"R": 400, "M": 500, "SB": 600}  # source OTF suffix -> CSS font-weight

SAFETY = "".join(chr(c) for c in range(0x20, 0x7F)) + "©·–—…“”‘’「」『』（）、，。：；！？％　"

# Fallback blocks as half-open code-point spans [start, end).
FALLBACK_BLOCKS = (
    [(0x0000, 0x3000), (0x3000, 0x4E00)]
    + [(start, start + 0x200) for start in range(0x4E00, 0xA000, 0x200)]
    + [(0xF900, 0x10000)]
)
BIG5_LEAD_BYTES = [*range(0xA4, 0xC7), *range(0xC9, 0xFA)]  # common + less common characters
BIG5_TRAIL_BYTES = [*range(0x40, 0x7F), *range(0xA1, 0xFF)]

CSS_BEGIN = "/* BEGIN font-face (generated by subset_fonts.py; do not edit by hand) */"
CSS_END = "/* END font-face */"
CSS_NOTE = (
    "/* Fallback blocks come first and the main subsets last. Browsers check the\n"
    "   last matching rule first, so they use the main subset for every character\n"
    "   it holds and fetch a fallback block only for a character it lacks. */\n"
)


# ── characters ───────────────────────────────────────────────────────────────

def site_chars():
    """Code points of every character in the site's pages, plus SAFETY."""
    chars = set(SAFETY)
    for page in sorted(ROOT.glob("*.html")) + sorted(ROOT.glob("*.qmd")):
        chars.update(html.unescape(page.read_text(encoding="utf-8", errors="ignore")))
    return {ord(ch) for ch in chars - set("\n\r\t")}


def font_codepoints(path):
    return set(TTFont(path, lazy=True).getBestCmap())


def big5_codepoints():
    codepoints = set()
    for lead in BIG5_LEAD_BYTES:
        for trail in BIG5_TRAIL_BYTES:
            try:
                codepoints.add(ord(bytes([lead, trail]).decode("big5")))
            except UnicodeDecodeError:
                pass
    return codepoints


def is_ideograph(cp):
    return 0x3400 <= cp <= 0x9FFF or 0xF900 <= cp <= 0xFAFF


def is_control(cp):
    return cp < 0x20 or 0x7F <= cp < 0xA0


def fallback_blocks(font_cps):
    """{block start: code points}: the font's symbols and Big5 ideographs, by block.

    Control characters stay out: pages contain newlines and tabs, and listing
    them would make every page download the first block."""
    big5 = big5_codepoints()
    wanted = {cp for cp in font_cps
              if not is_control(cp) and (cp in big5 or not is_ideograph(cp))}
    blocks = {start: {cp for cp in wanted if start <= cp < end} for start, end in FALLBACK_BLOCKS}
    return {start: cps for start, cps in blocks.items() if cps}


# ── font files ───────────────────────────────────────────────────────────────

def source_otf(weight):
    return FONT_DIR / f"{FONT_NAME}-{weight}.otf"


def main_subset(weight):
    return FONT_DIR / f"{FONT_NAME}-{weight}-sub.woff2"


def fallback_file(weight, start):
    return FALLBACK_DIR / f"{FONT_NAME}-{weight}-{start:04X}.woff2"


def build_subset(job):
    source, codepoints, out = job
    options = subset.Options()
    options.flavor = "woff2"
    options.layout_features = ["*"]
    font = subset.load_font(str(source), options)
    subsetter = subset.Subsetter(options)
    subsetter.populate(unicodes=codepoints)
    subsetter.subset(font)
    subset.save_font(font, str(out), options)
    return out


def run_jobs(jobs):
    with ProcessPoolExecutor(max_workers=os.cpu_count()) as pool:
        for out in pool.map(build_subset, jobs):
            print(f"  built {out.relative_to(ROOT)} ({out.stat().st_size // 1024} KB)")


def main_jobs(chars):
    return [(source_otf(weight), chars, main_subset(weight)) for weight in WEIGHTS]


def fallback_jobs():
    FALLBACK_DIR.mkdir(exist_ok=True)
    return [
        (source_otf(weight), cps, fallback_file(weight, start))
        for weight in WEIGHTS
        for start, cps in fallback_blocks(font_codepoints(source_otf(weight))).items()
    ]


# ── styles.css ───────────────────────────────────────────────────────────────

def versioned_url(path):
    digest = hashlib.sha1(path.read_bytes()).hexdigest()[:10]
    return f"{path.relative_to(ROOT).as_posix()}?v={digest}"


def unicode_range(codepoints):
    """CSS unicode-range value, merging runs of consecutive code points."""
    runs = []
    for cp in sorted(codepoints):
        if runs and cp == runs[-1][1] + 1:
            runs[-1][1] = cp
        else:
            runs.append([cp, cp])
    text = ", ".join(f"U+{a:X}" if a == b else f"U+{a:X}-{b:X}" for a, b in runs)
    return textwrap.fill(text, width=100, subsequent_indent="    ",
                         break_on_hyphens=False, break_long_words=False)


def font_face(path, weight, codepoints):
    return (
        "@font-face {\n"
        f"  font-family: '{FAMILY}';\n"
        f"  src: url('{versioned_url(path)}') format('woff2');\n"
        f"  font-weight: {WEIGHTS[weight]};\n"
        "  font-style: normal;\n"
        f"  unicode-range: {unicode_range(codepoints)};\n"
        "}\n"
    )


def is_ideograph_block(start):
    return 0x4E00 <= start < 0xA000


def fallback_range(path, start, end):
    """The whole span for an ideograph block. A symbol block lists only what it
    holds, because pages use symbols the font lacks (the ☾ theme toggle) and a
    span would make every page download that block for nothing."""
    return range(start, end) if is_ideograph_block(start) else font_codepoints(path)


def fallback_faces():
    return [
        font_face(path, weight, fallback_range(path, start, end))
        for weight in WEIGHTS
        for start, end in FALLBACK_BLOCKS
        if (path := fallback_file(weight, start)).exists()
    ]


def main_faces():
    return [font_face(main_subset(w), w, font_codepoints(main_subset(w))) for w in WEIGHTS]


def write_stylesheet():
    css = STYLESHEET.read_text(encoding="utf-8")
    block = re.compile(re.escape(CSS_BEGIN) + ".*?" + re.escape(CSS_END), re.S)
    if not block.search(css):
        sys.exit(f"styles.css lacks the generated block ({CSS_BEGIN} ... {CSS_END}).")
    faces = "\n".join([CSS_BEGIN, CSS_NOTE, *fallback_faces(), *main_faces(), CSS_END])
    STYLESHEET.write_text(block.sub(lambda _: faces, css, count=1), encoding="utf-8")
    print("  rewrote the @font-face block in styles.css")


# ── entry point ──────────────────────────────────────────────────────────────

def check():
    """List characters the pages use and the font has, but a main subset lacks."""
    shipped = set.intersection(*(font_codepoints(main_subset(w)) for w in WEIGHTS))
    missing = (site_chars() & font_codepoints(source_otf("R"))) - shipped
    if missing:
        print("Missing from the main subsets:", "".join(chr(cp) for cp in sorted(missing)))
        return 1
    print("The main subsets cover every character on the site.")
    return 0


def require_sources():
    absent = [source_otf(w).name for w in WEIGHTS if not source_otf(w).exists()]
    if absent:
        sys.exit(f"Missing source fonts in fonts/: {', '.join(absent)}")


def parse_args():
    parser = argparse.ArgumentParser(description="Rebuild the GenWanMin web fonts.")
    parser.add_argument("--fallback", action="store_true", help="also rebuild the fallback blocks")
    parser.add_argument("--check", action="store_true", help="only list characters the main subsets lack")
    return parser.parse_args()


def main():
    args = parse_args()
    require_sources()
    if args.check:
        return check()
    chars = site_chars()
    print(f"Collected {len(chars)} characters from the pages.")
    run_jobs(main_jobs(chars) + (fallback_jobs() if args.fallback else []))
    write_stylesheet()
    return check()


if __name__ == "__main__":
    sys.exit(main())
