#!/usr/bin/env python3
"""
Rebuild the GenWanMin (源雲明體) web fonts and their @font-face rules.

The site uses two weights, R (400) and SB (600). Each ships in two layers.

Main layer: every character the site's pages use, split so that a page
downloads only the files holding characters it shows.

  fonts/GenWanMin2TW-<w>-core.woff2
      Latin letters, digits, punctuation and symbols, plus the few Chinese
      characters the English home page shows. Every page needs it, and the
      English pages without Chinese text need nothing else.
  fonts/GenWanMin2TW-<w>-cjk<n>.woff2
      The other Chinese characters, CHARS_PER_SHARD to a file. Characters
      shown on many pages come first, and characters shown on the same pages
      share a file, so each page needs only some of these files.

Fallback layer:

  fonts/fallback/GenWanMin2TW-<w>-<start>.woff2
      All Big5 Traditional Chinese characters and the font's symbols, cut
      into code-point blocks. A browser fetches a block only when a page
      shows a character the main layer lacks, so text added since the last
      rebuild still appears in GenWanMin instead of a system font.

The script also rewrites the generated @font-face block in styles.css. The
main layer comes last there, with exact unicode-ranges, so browsers check it
first and use a fallback block only for characters it does not hold. Every
rule sets font-display: swap, so text shows at once in a system font and
switches to GenWanMin when the font arrives. Font URLs carry a content hash,
so browsers refetch a font only when it changes.

Rerun after adding text, especially new Chinese characters, so the main
layer covers every page again.

Requires: fonttools, brotli   ->   pip install fonttools brotli

Usage:  python3 subset_fonts.py              rebuild the main layer and styles.css
        python3 subset_fonts.py --fallback   also rebuild the fallback blocks
        python3 subset_fonts.py --check      list page characters the main layer lacks
"""
import argparse
import hashlib
import html
import os
import pathlib
import re
import sys
import textwrap
from concurrent.futures import ProcessPoolExecutor
from html.parser import HTMLParser

from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = pathlib.Path(__file__).resolve().parent
FONT_DIR = ROOT / "fonts"
FALLBACK_DIR = FONT_DIR / "fallback"
STYLESHEET = ROOT / "styles.css"
HEADER = ROOT / "_header.html"

FAMILY = "MyFont"
FONT_NAME = "GenWanMin2TW"
WEIGHTS = {"R": 400, "SB": 600}  # source OTF suffix -> CSS font-weight

SAFETY = "".join(chr(c) for c in range(0x20, 0x7F)) + "©·–—…“”‘’「」『』（）、，。：；！？％　"
LANDING_PAGE = "index.html"
LANGUAGE_TOGGLE_LABEL = "中"  # _header.html's script shows it on the English pages
CHARS_PER_SHARD = 60

# Fallback blocks as half-open code-point spans [start, end).
FALLBACK_BLOCKS = (
    [(0x0000, 0x3000), (0x3000, 0x4E00)]
    + [(start, start + 0x200) for start in range(0x4E00, 0xA000, 0x200)]
    + [(0xF900, 0x10000)]
)
BIG5_LEAD_BYTES = [*range(0xA4, 0xC7), *range(0xC9, 0xFA)]  # common + less common characters
BIG5_TRAIL_BYTES = [*range(0x40, 0x7F), *range(0xA1, 0xFF)]

CSS_BEGIN = "/* BEGIN font-face (generated by subset_fonts.py; do not edit by hand) */"
CSS_END = "/* END font-face */"
CSS_NOTE = (
    "/* Fallback blocks come first and the main layer last. Browsers check the\n"
    "   last matching rule first, so they use the main layer for every character\n"
    "   it holds and fetch a fallback block only for a character it lacks. */\n"
)


# ── characters ───────────────────────────────────────────────────────────────

def site_chars():
    """Code points of every character in the site's pages, plus SAFETY."""
    chars = set(SAFETY)
    for page in sorted(ROOT.glob("*.html")) + sorted(ROOT.glob("*.qmd")):
        chars.update(html.unescape(page.read_text(encoding="utf-8", errors="ignore")))
    return {ord(ch) for ch in chars - set("\n\r\t")}


def is_ideograph(cp):
    return 0x3400 <= cp <= 0x9FFF or 0xF900 <= cp <= 0xFAFF


def is_control(cp):
    return cp < 0x20 or 0x7F <= cp < 0xA0


class VisibleText(HTMLParser):
    """Collects a page's displayed text. On a Chinese page it also collects
    the data-zh attributes, which _header.html's script swaps in."""

    HIDDEN = {"head", "script", "style", "template"}

    def __init__(self, chinese):
        super().__init__(convert_charrefs=True)
        self.chinese = chinese
        self.hidden_depth = 0
        self.chunks = []

    def handle_starttag(self, tag, attrs):
        if tag in self.HIDDEN:
            self.hidden_depth += 1
        if self.chinese:
            self.chunks += [visible_text(value) for name, value in attrs if name == "data-zh" and value]

    def handle_endtag(self, tag):
        if tag in self.HIDDEN:
            self.hidden_depth -= 1

    def handle_data(self, data):
        if not self.hidden_depth:
            self.chunks.append(data)


def visible_text(markup, chinese=False):
    parser = VisibleText(chinese)
    parser.feed(markup)
    parser.close()
    return "".join(parser.chunks)


def header_script_labels():
    """The quoted strings in _header.html, which hold the Chinese navbar labels."""
    return "".join(re.findall(r"'([^'\n]*)'", HEADER.read_text(encoding="utf-8")))


def is_chinese_page(page):
    return page.stem.endswith("-zh")


def shown_chars(page):
    """Code points a rendered page shows, an estimate used to group characters."""
    chinese = is_chinese_page(page)
    text = visible_text(page.read_text(encoding="utf-8", errors="ignore"), chinese)
    text += header_script_labels() if chinese else LANGUAGE_TOGGLE_LABEL
    return {ord(ch) for ch in text}


def rendered_pages():
    return [page for page in sorted(ROOT.glob("*.html")) if not page.name.startswith("_")]


def big5_codepoints():
    codepoints = set()
    for lead in BIG5_LEAD_BYTES:
        for trail in BIG5_TRAIL_BYTES:
            try:
                codepoints.add(ord(bytes([lead, trail]).decode("big5")))
            except UnicodeDecodeError:
                pass
    return codepoints


# ── main layer plan ──────────────────────────────────────────────────────────

def sharing_order(chars_by_page):
    """Sort key: characters shown on many pages first, and characters shown
    on the same set of pages next to each other."""
    names = sorted(chars_by_page)

    def key(cp):
        pages = tuple(name for name in names if cp in chars_by_page[name])
        return (-len(pages), pages, cp)

    return key


def plan_main_layer(codepoints, chars_by_page):
    """{part name: code points}: the core first, then the Chinese shards."""
    ideographs = {cp for cp in codepoints if is_ideograph(cp)}
    core = (codepoints - ideographs) | (ideographs & chars_by_page[LANDING_PAGE])
    ordered = sorted(ideographs - core, key=sharing_order(chars_by_page))
    shards = [ordered[i:i + CHARS_PER_SHARD] for i in range(0, len(ordered), CHARS_PER_SHARD)]
    return {"core": core, **{f"cjk{n}": set(shard) for n, shard in enumerate(shards, 1)}}


def plan_all_weights():
    chars = site_chars()
    chars_by_page = {page.name: shown_chars(page) for page in rendered_pages()}
    return {weight: plan_main_layer(chars & font_codepoints(source_otf(weight)), chars_by_page)
            for weight in WEIGHTS}


# ── font files ───────────────────────────────────────────────────────────────

def font_codepoints(path):
    return set(TTFont(path, lazy=True).getBestCmap())


def source_otf(weight):
    return FONT_DIR / f"{FONT_NAME}-{weight}.otf"


def main_file(weight, part):
    return FONT_DIR / f"{FONT_NAME}-{weight}-{part}.woff2"


def fallback_file(weight, start):
    return FALLBACK_DIR / f"{FONT_NAME}-{weight}-{start:04X}.woff2"


def fallback_blocks(font_cps):
    """{block start: code points}: the font's symbols and Big5 ideographs, by block.

    Control characters stay out: pages contain newlines and tabs, and listing
    them would make every page download the first block."""
    big5 = big5_codepoints()
    wanted = {cp for cp in font_cps
              if not is_control(cp) and (cp in big5 or not is_ideograph(cp))}
    blocks = {start: {cp for cp in wanted if start <= cp < end} for start, end in FALLBACK_BLOCKS}
    return {start: cps for start, cps in blocks.items() if cps}


def build_subset(job):
    source, codepoints, out = job
    options = subset.Options()
    options.flavor = "woff2"
    options.layout_features = ["*"]
    font = subset.load_font(str(source), options)
    subsetter = subset.Subsetter(options)
    subsetter.populate(unicodes=codepoints)
    subsetter.subset(font)
    subset.save_font(font, str(out), options)
    return out


def run_jobs(jobs):
    with ProcessPoolExecutor(max_workers=os.cpu_count()) as pool:
        for out in pool.map(build_subset, jobs):
            print(f"  built {out.relative_to(ROOT)} ({out.stat().st_size // 1024} KB)")


def main_jobs(plan):
    return [(source_otf(weight), cps, main_file(weight, part))
            for weight, parts in plan.items()
            for part, cps in parts.items()]


def fallback_jobs():
    FALLBACK_DIR.mkdir(exist_ok=True)
    return [
        (source_otf(weight), cps, fallback_file(weight, start))
        for weight in WEIGHTS
        for start, cps in fallback_blocks(font_codepoints(source_otf(weight))).items()
    ]


def remove_stale(directory, kept):
    """Delete the woff2 files in directory that the current build did not write."""
    for path in sorted(set(directory.glob("*.woff2")) - set(kept)):
        try:
            path.unlink()
            print(f"  removed stale {path.relative_to(ROOT)}")
        except OSError:
            print(f"  could not remove stale {path.relative_to(ROOT)}; it is unused, delete it by hand")


# ── styles.css ───────────────────────────────────────────────────────────────

def versioned_url(path):
    digest = hashlib.sha1(path.read_bytes()).hexdigest()[:10]
    return f"{path.relative_to(ROOT).as_posix()}?v={digest}"


def unicode_range(codepoints):
    """CSS unicode-range value, merging runs of consecutive code points."""
    runs = []
    for cp in sorted(codepoints):
        if runs and cp == runs[-1][1] + 1:
            runs[-1][1] = cp
        else:
            runs.append([cp, cp])
    text = ", ".join(f"U+{a:X}" if a == b else f"U+{a:X}-{b:X}" for a, b in runs)
    return textwrap.fill(text, width=100, subsequent_indent="    ",
                         break_on_hyphens=False, break_long_words=False)


def font_face(path, weight, codepoints):
    return (
        "@font-face {\n"
        f"  font-family: '{FAMILY}';\n"
        f"  src: url('{versioned_url(path)}') format('woff2');\n"
        f"  font-weight: {WEIGHTS[weight]};\n"
        "  font-style: normal;\n"
        "  font-display: swap;\n"
        f"  unicode-range: {unicode_range(codepoints)};\n"
        "}\n"
    )


def is_ideograph_block(start):
    return 0x4E00 <= start < 0xA000


def fallback_range(path, start, end):
    """The whole span for an ideograph block. A symbol block lists only what it
    holds, because pages use symbols the font lacks (the ☾ theme toggle) and a
    span would make every page download that block for nothing."""
    return range(start, end) if is_ideograph_block(start) else font_codepoints(path)


def fallback_faces():
    return [
        font_face(path, weight, fallback_range(path, start, end))
        for weight in WEIGHTS
        for start, end in FALLBACK_BLOCKS
        if (path := fallback_file(weight, start)).exists()
    ]


def main_faces(plan):
    return [font_face(path, weight, font_codepoints(path))
            for weight, parts in plan.items()
            for path in (main_file(weight, part) for part in parts)]


def write_stylesheet(plan):
    css = STYLESHEET.read_text(encoding="utf-8")
    block = re.compile(re.escape(CSS_BEGIN) + ".*?" + re.escape(CSS_END), re.S)
    if not block.search(css):
        sys.exit(f"styles.css lacks the generated block ({CSS_BEGIN} ... {CSS_END}).")
    faces = "\n".join([CSS_BEGIN, CSS_NOTE, *fallback_faces(), *main_faces(plan), CSS_END])
    STYLESHEET.write_text(block.sub(lambda _: faces, css, count=1), encoding="utf-8")
    print("  rewrote the @font-face block in styles.css")


def served_main_files(weight):
    """The main-layer files styles.css points to for one weight."""
    pattern = rf"url\('(fonts/{FONT_NAME}-{weight}-[^/']+\.woff2)\?v="
    return [ROOT / url for url in re.findall(pattern, STYLESHEET.read_text(encoding="utf-8"))]


# ── entry point ──────────────────────────────────────────────────────────────

def check():
    """List characters the pages use and the font has, but the main layer lacks."""
    shipped = set.intersection(*(
        set().union(*map(font_codepoints, served_main_files(weight))) for weight in WEIGHTS))
    missing = (site_chars() & font_codepoints(source_otf("R"))) - shipped
    if missing:
        print("Missing from the main layer:", "".join(chr(cp) for cp in sorted(missing)))
        return 1
    print("The main layer covers every character on the site.")
    return 0


def require_sources():
    absent = [source_otf(w).name for w in WEIGHTS if not source_otf(w).exists()]
    if absent:
        sys.exit(f"Missing source fonts in fonts/: {', '.join(absent)}")


def parse_args():
    parser = argparse.ArgumentParser(description="Rebuild the GenWanMin web fonts.")
    parser.add_argument("--fallback", action="store_true", help="also rebuild the fallback blocks")
    parser.add_argument("--check", action="store_true", help="only list characters the main layer lacks")
    return parser.parse_args()


def rebuild(with_fallback):
    plan = plan_all_weights()
    print(f"Planned {sum(map(len, plan.values()))} main-layer files.")
    main = main_jobs(plan)
    fallback = fallback_jobs() if with_fallback else []
    run_jobs(main + fallback)
    remove_stale(FONT_DIR, [out for _, _, out in main])
    if with_fallback:
        remove_stale(FALLBACK_DIR, [out for _, _, out in fallback])
    write_stylesheet(plan)


def main():
    args = parse_args()
    require_sources()
    if not args.check:
        rebuild(args.fallback)
    return check()


if __name__ == "__main__":
    sys.exit(main())
