---
title: "Research"
---

My research has primarily appeared in international journals in regional studies and agricultural economics, including well-recognized outlets such as Journal of Transport Geography, Transportation Research Part A, Part D, and Forest Policy and Economics. A complete list of publications is available in my [CV](https://yyliou.github.io/yyliou/yyliou-cv/yyliou-cv.pdf).

## Selected Publications

- [The causal effects of removing hook-turn regulation on road safety](https://doi.org/10.1016/j.tra.2026.104860). [**Transportation Research Part A: Policy and Practice**](https://www.sciencedirect.com/journal/transportation-research-part-a-policy-and-practice), 205, 104860, 2026 (with Chang). †\*\^⁺

- [The causal effect of monthly pass programs on public transportation and carbon emissions](http://doi.org/10.1016/j.trd.2025.104903). [**Transportation Research Part D: Transport and Environment**](https://www.sciencedirect.com/journal/transportation-research-part-d-transport-and-environment), 146, 104903, 2025 (with Kim, Chang, and Liou). †\^⁺

- [Forest diversity and the distribution of farm revenue - Empirical evidence from forest farms in Taiwan](http://doi.org/10.1016/j.forpol.2024.103411). [**Forest Policy and Economics**](https://www.sciencedirect.com/journal/forest-policy-and-economics), 171, 103411, 2025 (with Lee and Chang). ⁺

- [Does COVID-19 affect metro use in Taipei?](http://doi.org/10.1016/j.jtrangeo.2021.102954) [**Journal of Transport Geography**](https://www.sciencedirect.com/journal/journal-of-transport-geography), 91, 102954, 2021 (with Chang, Lee, and Yang). †\^⁺


*Note*: † Journals recommended by the NSTC, Division of Regional Studies and Geography; \* Journals recommended by the NSTC, Division of Economics. ^ Journals recommended by the NSTC, Division of Management II. ⁺ Journals ranked in the top 10% of their field based on the Journal Impact Factor.

## Additional Publications

- [Hotel recovery strategies in the post-COVID-19 era: evidence on revenue, employment, and labor market rigidity from Taiwan](https://archive.conscientiabeam.com/index.php/31/article/view/4940/9198). [**Journal of Tourism Management Research**](https://www.conscientiabeam.com/journal/31), 13(1), 148–162, 2026 (with Kim and Chang).

- [Traffic accidents of religious tourism](https://doi.org/10.1016/j.annale.2026.100209). [**Annals of Tourism Research Empirical Insights**](https://www.sciencedirect.com/journal/annals-of-tourism-research-empirical-insights), 7(1), 100209, 2026 (with Chang).

- [Rooftop Solar Energy Adoption and Farm Revenue](https://onlinelibrary.wiley.com/doi/abs/10.1002/agr.70035). [**Agribusiness**](https://onlinelibrary.wiley.com/journal/15206297), 2025 (with Chang, Forthcoming).

- [The impact of the carbon border adjustment mechanism policy on international trade and market competition – A theoretical justification](https://www.worldscientific.com/doi/10.1142/S0217590825500328). [**Singapore Economic Review**](https://www.worldscientific.com/worldscinet/ser), 2025 (with Chang and Begun, Forthcoming).

- [Is Solar Panel Adoption a Win–Win Strategy for Chicken Farms? Evidence from Agriculture Census Data](https://www.mdpi.com/2077-0472/15/20/2124). [**Agriculture**](https://www.mdpi.com/journal/agriculture), 15(20), 2124, 2025 (with Lee and Chang).

- [How do consumers respond to COVID-19? Application of Bayesian approach on credit card transaction data](https://link.springer.com/article/10.1007/s11135-024-01915-9). [**Quality & Quantity**](https://link.springer.com/journal/11135), 58(6), 5737–5754, 2024 (with Chang and Just).

## Work in Progress

### Revision & Resubmission

- Food Traceability Systems and the Use of Chemical Fertilizers and Pesticides — Empirical Evidence Using Plot and Farm Household Data (with Chang).
- Does the Development of Aquavoltaics Production Affect Farmland Price? (with Chang).
- Air Pollution during Religious Holidays: Evidence from Tomb-Sweeping Day (with Chang and Meyerhoefer).

### Under Review

- Technology Adoption of Environmentally Controlled Housing System and the Distribution of Farm Revenue (with Chang).
- The Effects of Enhancing Pedestrian-Protective Infrastructure on Intersection Safety (with Chang).
- Pension Policy Reform of the Minimum Contribution Period and Intra-household Succession of Family Farms (with Chang).
- Air Quality vs. Fiscal Compensation: Evidence from Coal Reduction and Housing Markets (with Chang and Zilberman).
- Do Consumption Vouchers Benefit Agricultural Cooperatives? Causal Evidence from Farmers' Associations (with Chang and Wu).

## Co-Authors

- [Begun, Jeffrey C.](https://jsis.washington.edu/emis/people/jeffrey-begun/), University of Washington.
- [Chang, Hung-Hao](https://sites.google.com/view/hh-chang), National Taiwan University.
- [Just, David R.](https://economics.cornell.edu/david-just), Cornell University.
- [Kim, Man-Keun](https://qanr.usu.edu/directory/kim-man-keun), Utah State University.
- [Lee, Brian](https://cpree.princeton.edu/people/brian-lee), Princeton University.
- Lee, Tzong-Haw, Xiamen University of Technology.
- [Liou, Ruey-Wan](https://www.agec.ntu.edu.tw/en/teacher/teacher2/Ruey-Wan-Liou-30120496), National Taiwan University.
- [Meyerhoefer, Chad D.](https://business.lehigh.edu/directory/chad-d-meyerhoefer), Lehigh University.
- [Wu, Karin](https://www.agec.ntu.edu.tw/en/teacher/KARIN-WU-38174358), National Taiwan University.
- [Yang, Feng-An](https://www.agec.ntu.edu.tw/en/teacher/Feng-An-Yang-84600801), National Taiwan University.
- [Zilberman, David](https://professorzilberman.com), University of California, Berkeley.

*Note*: Names are listed in alphabetical order.
